# IPL Data Analysis

## 1. Import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

## 2. Load Dataset

In [2]:
ipl_df = pd.read_csv("data/matches.csv")
ipl_df.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

## 3. Data Exploratin

In [3]:
ipl_df.shape

(756, 18)

In [4]:
ipl_df.dtypes

id                 int64
season             int64
city                 str
date                 str
team1                str
team2                str
toss_winner          str
toss_decision        str
result               str
dl_applied         int64
winner               str
win_by_runs        int64
win_by_wickets     int64
player_of_match      str
venue                str
umpire1              str
umpire2              str
umpire3              str
dtype: object

In [5]:
ipl_df.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [6]:
ipl_df.duplicated().sum()

np.int64(0)

In [7]:
ipl_df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,756.0,1792.178571,3464.478148,1.0,189.75,378.5,567.25,11415.0
season,756.0,2013.444444,3.366895,2008.0,2011.00,2013.0,2016.00,2019.0
dl_applied,756.0,0.025132,0.156630,0.0,0.00,0.0,0.00,1.0
win_by_runs,756.0,13.283069,23.471144,0.0,0.00,0.0,19.00,146.0
win_by_wickets,756.0,3.350529,3.387963,0.0,0.00,4.0,6.00,10.0

# 4.Data Cleaning

## 4.1 Drop umpire3 column

In [8]:
ipl_df.drop(columns=["umpire3"], inplace=True)
ipl_df.isnull().sum()

id                 0
season             0
city               7
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
result             0
dl_applied         0
winner             4
win_by_runs        0
win_by_wickets     0
player_of_match    4
venue              0
umpire1            2
umpire2            2
dtype: int64

## 4.2 Check missing winner data

In [9]:
ipl_df[ipl_df["winner"].isna()]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
300,301,2011,Delhi,2011-05-21,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,no result,0,NaN,0,0,NaN,Feroz Shah Kotla,SS Hazare,RJ Tucker
545,546,2015,Bangalore,2015-04-29,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,NaN,0,0,NaN,M Chinnaswamy Stadium,JD Cloete,PG Pathak
570,571,2015,Bangalore,2015-05-17,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,no result,0,NaN,0,0,NaN,M Chinnaswamy Stadium,HDPK Dharmasena,K Srinivasan
744,11340,2019,Bengaluru,30/04/19,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,NaN,0,0,NaN,M. Chinnaswamy Stadium,Nigel Llong,Ulhas Gandhe

## 4.3 Check missing player of the match data

In [10]:
ipl_df[ipl_df["player_of_match"].isna()]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
300,301,2011,Delhi,2011-05-21,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,no result,0,NaN,0,0,NaN,Feroz Shah Kotla,SS Hazare,RJ Tucker
545,546,2015,Bangalore,2015-04-29,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,NaN,0,0,NaN,M Chinnaswamy Stadium,JD Cloete,PG Pathak
570,571,2015,Bangalore,2015-05-17,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,no result,0,NaN,0,0,NaN,M Chinnaswamy Stadium,HDPK Dharmasena,K Srinivasan
744,11340,2019,Bengaluru,30/04/19,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,NaN,0,0,NaN,M. Chinnaswamy Stadium,Nigel Llong,Ulhas Gandhe

## 4.4 Check missing city data

In [11]:
ipl_df[ipl_df["city"].isna()]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
461,462,2014,NaN,2014-04-19,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,7,PA Patel,Dubai International Cricket Stadium,Aleem Dar,AK Chaudhary
462,463,2014,NaN,2014-04-19,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,normal,0,Delhi Daredevils,0,4,JP Duminy,Dubai International Cricket Stadium,Aleem Dar,VA Kulkarni
466,467,2014,NaN,2014-04-23,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,normal,0,Chennai Super Kings,7,0,RA Jadeja,Dubai International Cricket Stadium,HDPK Dharmasena,RK Illingworth
468,469,2014,NaN,2014-04-25,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,4,0,AJ Finch,Dubai International Cricket Stadium,M Erasmus,S Ravi
469,470,2014,NaN,2014-04-25,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Chennai Super Kings,0,7,MM Sharma,Dubai International Cricket Stadium,BF Bowden,M Erasmus
474,475,2014,NaN,2014-04-28,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,5,Sandeep Sharma,Dubai International Cricket Stadium,BF Bowden,S Ravi
476,477,2014,NaN,2014-04-30,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Sunrisers Hyderabad,15,0,B Kumar,Dubai International Cricket Stadium,HDPK Dharmasena,M Erasmus

In [12]:
ipl_df.loc[ipl_df["city"].isna(), "city"] = "Dubai"

In [13]:
ipl_df["city"].isna().sum()

np.int64(0)

## 4.5 Check missing umpire1 and umpire2 data

In [14]:
ipl_df[ipl_df["umpire1"].isna()]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN

In [15]:
ipl_df[ipl_df["umpire2"].isna()]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN

In [16]:
ipl_df.isnull().sum()

id                 0
season             0
city               0
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
result             0
dl_applied         0
winner             4
win_by_runs        0
win_by_wickets     0
player_of_match    4
venue              0
umpire1            2
umpire2            2
dtype: int64

# 5. Check Date Type

In [17]:
ipl_df.dtypes

id                 int64
season             int64
city                 str
date                 str
team1                str
team2                str
toss_winner          str
toss_decision        str
result               str
dl_applied         int64
winner               str
win_by_runs        int64
win_by_wickets     int64
player_of_match      str
venue                str
umpire1              str
umpire2              str
dtype: object

In [18]:
ipl_df["date"] = pd.to_datetime(ipl_df["date"], errors="coerce")
ipl_df["date"].dtype

dtype('<M8[us]')

# 6. Check Data Consistency

In [19]:
print(ipl_df["team1"].unique())
print("-----------------------------------------------------------")
print(ipl_df["team2"].unique())
print("-----------------------------------------------------------")
print(ipl_df["winner"].unique())
print("-----------------------------------------------------------")
print(ipl_df["toss_winner"].unique())

<StringArray>
[        'Sunrisers Hyderabad',              'Mumbai Indians',
               'Gujarat Lions',      'Rising Pune Supergiant',
 'Royal Challengers Bangalore',       'Kolkata Knight Riders',
            'Delhi Daredevils',             'Kings XI Punjab',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors',     'Rising Pune Supergiants',
              'Delhi Capitals']
Length: 15, dtype: str
-----------------------------------------------------------
<StringArray>
['Royal Challengers Bangalore',      'Rising Pune Supergiant',
       'Kolkata Knight Riders',             'Kings XI Punjab',
            'Delhi Daredevils',         'Sunrisers Hyderabad',
              'Mumbai Indians',               'Gujarat Lions',
            'Rajasthan Royals',         'Chennai Super Kings',
             'Deccan Chargers',               'Pune Warriors',
        'Kochi Tuskers Kerala',     'Rising Pune Supergiants',
              'Delhi Capitals']
Length: 15, dtype: str
-----------------------------------------------------------
<StringArray>
[        'Sunrisers Hyderabad',      'Rising Pune Supergiant',
       'Kolkata Knight Riders',             'Kings XI Punjab',
 'Royal Challengers Bangalore',              'Mumbai Indians',
            'Delhi Daredevils',               'Gujarat Lions',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',               'Pune Warriors',
        'Kochi Tuskers Kerala',                           nan,
     'Rising Pune Supergiants',              'Delhi Capitals']
Length: 16, dtype: str
-----------------------------------------------------------
<StringArray>
['Royal Challengers Bangalore',      'Rising Pune Supergiant',
       'Kolkata Knight Riders',             'Kings XI Punjab',
         'Sunrisers Hyderabad',              'Mumbai Indians',
               'Gujarat Lions',            'Delhi Daredevils',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors',     'Rising Pune Supergiants',
              'Delhi Capitals']
Length: 15, dtype: str

In [20]:
replace_data = {
    "Rising Pune Supergiant" : "Rising Pune Supergiants",
    "Delhi Daredevils" : "Delhi Capitals"
}

columns = ["team1", "team2", "winner", "toss_winner"]

for col in columns:
    ipl_df[col] = ipl_df[col].replace(replace_data)
    print(ipl_df[col].unique())

<StringArray>
[        'Sunrisers Hyderabad',              'Mumbai Indians',
               'Gujarat Lions',     'Rising Pune Supergiants',
 'Royal Challengers Bangalore',       'Kolkata Knight Riders',
              'Delhi Capitals',             'Kings XI Punjab',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors']
Length: 13, dtype: str
<StringArray>
['Royal Challengers Bangalore',     'Rising Pune Supergiants',
       'Kolkata Knight Riders',             'Kings XI Punjab',
              'Delhi Capitals',         'Sunrisers Hyderabad',
              'Mumbai Indians',               'Gujarat Lions',
            'Rajasthan Royals',         'Chennai Super Kings',
             'Deccan Chargers',               'Pune Warriors',
        'Kochi Tuskers Kerala']
Length: 13, dtype: str
<StringArray>
[        'Sunrisers Hyderabad',     'Rising Pune Supergiants',
       'Kolkata Knight Riders',             'Kings XI Punjab',
 'Royal Challengers Bangalore',              'Mumbai Indians',
              'Delhi Capitals',               'Gujarat Lions',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',               'Pune Warriors',
        'Kochi Tuskers Kerala',                           nan]
Length: 14, dtype: str
<StringArray>
['Royal Challengers Bangalore',     'Rising Pune Supergiants',
       'Kolkata Knight Riders',             'Kings XI Punjab',
         'Sunrisers Hyderabad',              'Mumbai Indians',
               'Gujarat Lions',              'Delhi Capitals',
         'Chennai Super Kings',            'Rajasthan Royals',
             'Deccan Chargers',        'Kochi Tuskers Kerala',
               'Pune Warriors']
Length: 13, dtype: str

In [21]:
ipl_df["toss_decision"].value_counts()

toss_decision
field    463
bat      293
Name: count, dtype: int64

# 7. Feature Engineering

In [22]:
ipl_df['toss_match_win'] = (ipl_df['toss_winner'] == ipl_df['winner'])
ipl_df['toss_match_win']

0      False
1       True
2       True
3       True
4       True
       ...
751     True
752    False
753     True
754     True
755     True
Name: toss_match_win, Length: 756, dtype: bool